version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    command: nodemon --inspect-brk=0.0.0.0:9229
    volumes:
      - .:/var/www/app
    ports:
      - '80:3000'
      - '9229:9229'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'